### PR TITLE
Volume 9

### PR DESCRIPTION
**Pull request by chaselgrove**
@PeerHerholz please will you check that Volume 9 has been converted properly?

### CODE REVIEW

**Comment by PeerHerholz** [comment]
Hi @chaselgrove,

sure thing. What would be the preferred workflow for this? Check online in the docs (couldn't find a link to the respective sphinx website) or build them locally?

**Comment by chaselgrove** [comment]
Thanks!  Whatever's easiest -- with luck there won't be anything to fix. :)  I've put a built version at https://how-would.repronim.org/en/volume-9/ and you can just note any issues in this forum, or feel free to edit this branch if you'd rather.  (NB this PR is from chaselgrove:volume-9, but the build updates from repronim:volume-9.)

**Review by PeerHerholz — COMMENTED** [review]
Thanks for the link and the additional information.

Here are a few things I noticed:

- the last sentence of "In practice" (Windows users should consider using the Ubuntu subsystem (reference).) entails an unresolved reference
- IIRC `shape` should be renamed to `sulci` as requested by the ENIGMA collaborators (@dnkennedy)?
- the third sentence of "Step 2" (Instead we are going to utilize virtualization techniques (reference?)) entails an unresolved reference
- also in "Step 2", the sentence "While it’s possible to build Windows containers (REFERENCE), macOS is not supported (not to say that maybe somewhere in northern California (no, not Napa Valley, a bit below) this exists)." contains an unresolved reference
- further down, also in "Step 2", the sentence "Don’t give up, searching the world wide web and asking questions in suited forums like `www.neurostars.org <http://www.neurostars.org>`__ will lead to the answer! " includes an unresolved link
- there's same code here and there in the text and before I add those parts that are not rendered, we should talk about how we want to render it 
- the Appendix "generate_enigma-sulci_images.sh" is missing

**Comment by chaselgrove** [comment]
Thanks, @PeerHerholz .

At this point I just want to publish this in as close to the published Google doc as possible.  Given that the missing references, missing appendix, and other issues are present in the source document, I'll note those as issues in this repository.  If you had any changes in an upstream Google doc, let me know and I can bring those in.

**Pull request merged**
